# Node.js 공식 이미지를 베이스 이미지로 사용
FROM node:14

# 애플리케이션 디렉토리 생성
WORKDIR /app

# 애플리케이션 의존성 설치
# package.json과 package-lock.json을 모두 복사
COPY package*.json ./
RUN npm install

# 애플리케이션 소스 추가
COPY . .

# 애플리케이션 실행 포트 노출
EXPOSE 8080

# 애플리케이션 실행
CMD ["node", "index.js"]
