apiVersion: v1 # 사용할 Kubernetes API 버전을 지정합니다. 'v1'은 Core API 그룹에 속하며 기본적인 객체를 다룹니다.
kind: Service # 이 리소스의 종류를 지정합니다. Service는 네트워크 서비스로, 하나 이상의 Pod에 네트워크 액세스를 제공합니다.
metadata:
  name: node-app-service # Service의 이름을 지정합니다. 이 이름은 클러스터 내에서 유일해야 합니다.
spec: # Service 사양을 정의합니다.
  type: NodePort # Service 타입을 지정합니다. NodePort는 클러스터 내의 모든 노드에서 고정 포트(여기서는 30000)를 통해 서비스에 접근할 수 있게 합니다.
  ports:
    - port: 8080 # 서비스가 클러스터 내부에서 사용할 포트 번호를 지정합니다.
      targetPort: 8080 # 서비스 요청을 전달할 Pod의 포트 번호를 지정합니다. 이 포트는 Pod 내부의 애플리케이션이 사용하는 포트와 일치해야 합니다.
      nodePort: 30000 # 외부에서 서비스에 접근할 때 사용할 노드의 포트 번호를 지정합니다.
  selector:
    app: node-app # 이 서비스가 관리할 Pod을 선택하기 위한 레이블 셀렉터입니다. 여기서는 'app: node-app' 레이블을 가진 Pod을 선택합니다.
